// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // La CLI de Prisma (migrate, db pull...) usa la conexión DIRECTA
  // (puerto 5432). El pooler en modo transacción no soporta migraciones.
  datasource: {
    url: process.env.DIRECT_URL,
  },
});
